program NeatoToolio;
{$R *.dres}

uses
  madExcept,
  madLinkDisAsm,
  madListHardware,
  madListProcesses,
  madListModules,
  System.StartUpCopy,
  FMX.Forms,
  fmx.types,

  dmSerial.Windows in 'dmSerial.Windows.pas' {dmSerialWindows: TDataModule},
  dmSerial.Base in 'dmSerial.Base.pas' {dmSerialBase: TDataModule},
  dmSerial.TCPIP in 'dmSerial.TCPIP.pas' {dmSerialTCP: TDataModule},
  dmCommon in 'dmCommon.pas' {dm: TDataModule},
  formMain in 'formMain.pas' {frmMain},

  XSuperJSON in 'XSuperJSON\XSuperJSON.pas',
  XSuperObject in 'XSuperJSON\XSuperObject.pas',
  neato.Commands in 'common\neato.Commands.pas',
  neato.Errors in 'common\neato.Errors.pas',
  neato.Helpers in 'common\neato.Helpers.pas',
  neato.Settings in 'common\neato.Settings.pas',
  neato.D.ClearFiles in 'DSeries\neato.D.ClearFiles.pas',
  neato.D.GetAnalogSensors in 'DSeries\neato.D.GetAnalogSensors.pas',
  neato.D.GetButtons in 'DSeries\neato.D.GetButtons.pas',
  neato.D.GetCalInfo in 'DSeries\neato.D.GetCalInfo.pas',
  neato.D.GetCharger in 'DSeries\neato.D.GetCharger.pas',
  neato.D.GetDigitalSensors in 'DSeries\neato.D.GetDigitalSensors.pas',
  neato.D.GetErr in 'DSeries\neato.D.GetErr.pas',
  neato.D.GetMotors in 'DSeries\neato.D.GetMotors.pas',
  neato.D.GetUsage in 'DSeries\neato.D.GetUsage.pas',
  neato.D.GetUserSettings in 'DSeries\neato.D.GetUserSettings.pas',
  neato.D.GetVersion in 'DSeries\neato.D.GetVersion.pas',
  neato.D.GetWarranty in 'DSeries\neato.D.GetWarranty.pas',
  neato.D.GetWifiInfo in 'DSeries\neato.D.GetWifiInfo.pas',
  neato.D.GetWifiStatus in 'DSeries\neato.D.GetWifiStatus.pas',
  neato.XV.GetAnalogSensors in 'XVSeries\neato.XV.GetAnalogSensors.pas',
  neato.XV.GetCharger in 'XVSeries\neato.XV.GetCharger.pas',
  neato.DXV.Playsound in 'Common\neato.DXV.Playsound.pas',
  neato.XV.GetDigitalSensors in 'XVSeries\neato.XV.GetDigitalSensors.pas',
  neato.D.GetSensor in 'DSeries\neato.D.GetSensor.pas',
  frame.D.GetAnalogSensors in 'DSeriesFrames\frame.D.GetAnalogSensors.pas' {frameDGetAnalogSensors: TFrame},
  frame.D.GetButtons in 'DSeriesFrames\frame.D.GetButtons.pas' {frameDGetButtons: TFrame},
  frame.D.GetCalInfo in 'DSeriesFrames\frame.D.GetCalInfo.pas' {frameDGetCalInfo: TFrame},
  frame.D.GetCharger in 'DSeriesFrames\frame.D.GetCharger.pas' {frameDGetCharger: TFrame},
  frame.D.GetDigitalSensors in 'DSeriesFrames\frame.D.GetDigitalSensors.pas' {frameDGetDigitalSensors: TFrame},
  frame.D.GetMotors in 'DSeriesFrames\frame.D.GetMotors.pas' {frameDGetMotors: TFrame},
  frame.D.GetWarranty in 'DSeriesFrames\frame.D.GetWarranty.pas' {frameDGetWarranty: TFrame},
  frame.D.GetErr in 'DSeriesFrames\frame.D.GetErr.pas' {FrameDGetErr: TFrame},
  frame.D.GetVersion in 'DSeriesFrames\frame.D.GetVersion.pas' {frameDGetVersion: TFrame},
  frame.D.GetUsage in 'DSeriesFrames\frame.D.GetUsage.pas' {frameDGetUsage: TFrame},
  frame.D.GetUserSettings in 'DSeriesFrames\frame.D.GetUserSettings.pas' {frameDGetUserSettings: TFrame},
  frame.D.ClearFiles in 'DSeriesFrames\frame.D.ClearFiles.pas' {frameDClearFiles: TFrame},
  frame.D.GetWifiInfo in 'DSeriesFrames\frame.D.GetWifiInfo.pas' {frameDGetWifiInfo: TFrame},
  frame.D.GetWifiStatus in 'DSeriesFrames\frame.D.GetWifiStatus.pas' {frameDGetWifiStatus: TFrame},
  frame.XV.GetCharger in 'XVSeriesFrames\frame.XV.GetCharger.pas' {frameXVGetCharger: TFrame},
  frame.DXV.Terminal in 'CommonFrames\frame.DXV.Terminal.pas' {frameDXVTerminal: TFrame},
  frame.DXV.Playsound in 'CommonFrames\frame.DXV.Playsound.pas' {frameDXVPlaySound: TFrame},
  frame.XV.GetAnalogSensors in 'XVSeriesFrames\frame.XV.GetAnalogSensors.pas' {frameXVGetAnalogSensors: TFrame},
  frame.XV.GetDigitalSensors in 'XVSeriesFrames\frame.XV.GetDigitalSensors.pas' {frameXVGetDigitalSensors: TFrame},
  frame.D.GetSensors in 'DSeriesFrames\frame.D.GetSensors.pas' {frameDGetSensors: TFrame},
  neato.XV.GetMotors in 'XVSeries\neato.XV.GetMotors.pas',
  frame.XV.GetMotors in 'XVSeriesFrames\frame.XV.GetMotors.pas' {frameXVGetMotors: TFrame},
  frame.XV.GetCalInfo in 'XVSeriesFrames\frame.XV.GetCalInfo.pas' {frameXVGetCalInfo: TFrame},
  neato.XV.GetCalInfo in 'XVSeries\neato.XV.GetCalInfo.pas',
  frame.XV.GetWarranty in 'XVSeriesFrames\frame.XV.GetWarranty.pas' {frameXVGetWarranty: TFrame},
  neato.XV.GetWarranty in 'XVSeries\neato.XV.GetWarranty.pas',
  neato.XV.GetErr in 'XVSeries\neato.XV.GetErr.pas',
  frame.XV.GetErr in 'XVSeriesFrames\frame.XV.GetErr.pas' {FrameXVGetErr: TFrame},
  frame.XV.GetVersion in 'XVSeriesFrames\frame.XV.GetVersion.pas' {frameXVGetVersion: TFrame},
  neato.XV.GetVersion in 'XVSeries\neato.XV.GetVersion.pas',
  frame.XV.RestoreDefaults in 'XVSeriesFrames\frame.XV.RestoreDefaults.pas' {frameXVRestoreDefaults: TFrame},
  neato.XV.RestoreDefaults in 'XVSeries\neato.XV.RestoreDefaults.pas',
  neato.XV.GetButtons in 'XVSeries\neato.XV.GetButtons.pas',
  frame.XV.GetButtons in 'XVSeriesFrames\frame.XV.GetButtons.pas' {frameXVGetButtons: TFrame},
  neato.XV.GetTime in 'XVSeries\neato.XV.GetTime.pas',
  frame.XV.GetTime in 'XVSeriesFrames\frame.XV.GetTime.pas' {frameXVGetTime: TFrame},
  neato.XV.Clean in 'XVSeries\neato.XV.Clean.pas',
  frame.XV.Clean in 'XVSeriesFrames\frame.XV.Clean.pas' {frameXVClean: TFrame},
  neato.DXV.GetLDSScan in 'Common\neato.DXV.GetLDSScan.pas',
  frame.DXV.GetLDSScan in 'CommonFrames\frame.DXV.GetLDSScan.pas' {frameDXVGetLDSScan: TFrame},
  neato.DXV.SetFuelGauge in 'Common\neato.DXV.SetFuelGauge.pas',
  frame.DXV.SetFuelGauge in 'CommonFrames\frame.DXV.SetFuelGauge.pas' {frameDXVSetFuelGauge: TFrame},
  frame.DXV.GetAccel in 'CommonFrames\frame.DXV.GetAccel.pas' {frameDXVGetAccel: TFrame},
  neato.DXV.GetAccel in 'Common\neato.DXV.GetAccel.pas',
  neato.DXV.SetTime in 'Common\neato.DXV.SetTime.pas',
  frame.DXV.SetTime in 'CommonFrames\frame.DXV.SetTime.pas' {frameDXVSetTime: TFrame},
  frame.DXV.SetSystemMode in 'CommonFrames\frame.DXV.SetSystemMode.pas' {frameDXVSetSystemMode: TFrame},
  neato.DXV.SetSystemMode in 'Common\neato.DXV.SetSystemMode.pas',
  neato.DXV.SetLCD in 'Common\neato.DXV.SetLCD.pas',
  frame.DXV.SetLCD in 'CommonFrames\frame.DXV.SetLCD.pas' {frameDXVSetLCD: TFrame},
  neato.XV.SetLED in 'XVSeries\neato.XV.SetLED.pas',
  neato.XV.GetSchedule in 'XVSeries\neato.XV.GetSchedule.pas',
  frame.XV.GetSchedule in 'XVSeriesFrames\frame.XV.GetSchedule.pas' {frameXVGetSchedule: TFrame},
  frame.Master in 'CommonFrames\frame.Master.pas' {frameMaster: TFrame},
  frame.DXV.SetSchedule in 'CommonFrames\frame.DXV.SetSchedule.pas' {frameXVSetSchedule: TFrame},
  neato.DXV.SetSchedule in 'Common\neato.DXV.SetSchedule.pas',
  frame.DXV.SetWallFollower in 'CommonFrames\frame.DXV.SetWallFollower.pas' {frameDXVSetWallFollower: TFrame},
  neato.DXV.SetWallFollower in 'Common\neato.DXV.SetWallFollower.pas',
  frame.DXV.SetDistanceCal in 'CommonFrames\frame.DXV.SetDistanceCal.pas' {frameDXVSetDistanceCal: TFrame},
  neato.DXV.SetDistanceCal in 'Common\neato.DXV.SetDistanceCal.pas',
  frame.DXV.SetIEC in 'CommonFrames\frame.DXV.SetIEC.pas' {frameDXVSetIEC: TFrame},
  neato.DXV.SetIEC in 'Common\neato.DXV.SetIEC.pas',
  frame.DXV.GetLifeStatLog in 'CommonFrames\frame.DXV.GetLifeStatLog.pas' {frameDXVGetLifeStatLog: TFrame},
  neato.DXV.GetLifeStatLog in 'Common\neato.DXV.GetLifeStatLog.pas',
  neato.DXV.SetMotor in 'Common\neato.DXV.SetMotor.pas',
  frame.DXV.LidarView in 'CommonFrames\frame.DXV.LidarView.pas' {frameDXVLidarView: TFrame},
  frame.DXV.SetMotor in 'CommonFrames\frame.DXV.SetMotor.pas' {frameDXVSetMotor: TFrame},
  neato.DXV.TestLDS in 'Common\neato.DXV.TestLDS.pas',
  frame.DXV.TestLDS in 'CommonFrames\frame.DXV.TestLDS.pas' {frameDXVTestLDS: TFrame},
  frame.DXV.SetBatteryTest in 'CommonFrames\frame.DXV.SetBatteryTest.pas' {frameDXVSetBatteryTest: TFrame},
  neato.DXV.SetBatteryTest in 'Common\neato.DXV.SetBatteryTest.pas',
  frame.DXV.SetLanguage in 'CommonFrames\frame.DXV.SetLanguage.pas' {frameDXVSetLanguage: TFrame},
  neato.DXV.SetLanguage in 'Common\neato.DXV.SetLanguage.pas',
  neato.D.SetButton in 'DSeries\neato.D.SetButton.pas',
  frame.D.SetButton in 'DSeriesFrames\frame.D.SetButton.pas' {frameDSetButton: TFrame},
  neato.D.Clean in 'DSeries\neato.D.Clean.pas',
  frame.D.Clean in 'DSeriesFrames\frame.D.Clean.pas' {frameDClean: TFrame},
  frame.XV.SetLED in 'XVSeriesFrames\frame.XV.SetLED.pas' {frameXVSetLED: TFrame},
  frame.D.SetLED in 'DSeriesFrames\frame.D.SetLED.pas' {frameDSetLED: TFrame},
  neato.D.SetLED in 'DSeries\neato.D.SetLED.pas',
  frame.D.SetNTPTime in 'DSeriesFrames\frame.D.SetNTPTime.pas' {frameDSetNTPTime: TFrame},
  neato.D.SetNTPTime in 'DSeries\neato.D.SetNTPTime.pas',
  frame.D.SetNavigationMode in 'DSeriesFrames\frame.D.SetNavigationMode.pas' {frameDSetNavigationMode: TFrame},
  neato.D.SetNavigationMode in 'DSeries\neato.D.SetNavigationMode.pas',
  neato.D.SetUsage in 'DSeries\neato.D.SetUsage.pas',
  frame.D.SetUsage in 'DSeriesFrames\frame.D.SetUsage.pas' {frameDSetUsage: TFrame},
  frame.ScriptEngine in 'Scripts\frame.ScriptEngine.pas' {frameScriptEngine: TFrame};

{$R *.res}

begin
  Application.Initialize;
  Application.CreateForm(Tdm, dm);
  Application.CreateForm(TfrmMain, frmMain);
  Application.Run;
end.
